#!/usr/bin/env python3
"""
Test Jira Integration with Stub Server
Tests Assertly's Jira integration features
"""

import requests
import json
import time
import subprocess
import threading
import os

class JiraIntegrationTester:
    def __init__(self):
        self.jira_stub_url = "http://localhost:8080"
        self.assertly_url = "http://localhost:5000"
        self.jira_stub_process = None
        
    def start_jira_stub(self):
        """Start Jira stub server"""
        print("🚀 Starting Jira Stub Server...")
        self.jira_stub_process = subprocess.Popen(
            ['python3', 'jira_stub.py'],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        time.sleep(3)  # Wait for server to start
        print("✅ Jira Stub Server started")
        
    def stop_jira_stub(self):
        """Stop Jira stub server"""
        if self.jira_stub_process:
            self.jira_stub_process.terminate()
            self.jira_stub_process.wait()
            print("✅ Jira Stub Server stopped")
    
    def test_jira_stub_health(self):
        """Test Jira stub server health"""
        print("\n🔍 Testing Jira Stub Server Health...")
        try:
            response = requests.get(f"{self.jira_stub_url}/health", timeout=5)
            if response.status_code == 200:
                print("✅ Jira Stub Server is healthy")
                return True
            else:
                print(f"❌ Jira Stub Server health check failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Jira Stub Server not accessible: {e}")
            return False
    
    def test_jira_projects(self):
        """Test Jira projects endpoint"""
        print("\n🔍 Testing Jira Projects...")
        try:
            response = requests.get(f"{self.jira_stub_url}/rest/api/3/project", timeout=5)
            if response.status_code == 200:
                projects = response.json()
                print(f"✅ Found {len(projects)} projects")
                for project in projects:
                    print(f"  - {project['key']}: {project['name']}")
                return True
            else:
                print(f"❌ Projects endpoint failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Projects test failed: {e}")
            return False
    
    def test_jira_issues(self):
        """Test Jira issues search"""
        print("\n🔍 Testing Jira Issues...")
        try:
            # Test search with JQL
            response = requests.get(
                f"{self.jira_stub_url}/rest/api/3/search",
                params={'jql': 'project = TEST AND issuetype = Test'},
                timeout=5
            )
            if response.status_code == 200:
                data = response.json()
                issues = data.get('issues', [])
                print(f"✅ Found {len(issues)} test issues")
                for issue in issues:
                    print(f"  - {issue['key']}: {issue['summary']}")
                return True
            else:
                print(f"❌ Issues search failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Issues test failed: {e}")
            return False
    
    def test_jira_issue_creation(self):
        """Test creating Jira issues"""
        print("\n🔍 Testing Jira Issue Creation...")
        try:
            new_issue = {
                "fields": {
                    "project": {"key": "TEST"},
                    "summary": "Test Case: AI Generated Test",
                    "description": "This test case was generated by Assertly AI",
                    "issuetype": {"name": "Test"}
                }
            }
            
            response = requests.post(
                f"{self.jira_stub_url}/rest/api/3/issue",
                json=new_issue,
                headers={'Content-Type': 'application/json'},
                timeout=5
            )
            
            if response.status_code == 201:
                issue = response.json()
                print(f"✅ Created issue: {issue['key']}")
                return True
            else:
                print(f"❌ Issue creation failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Issue creation test failed: {e}")
            return False
    
    def test_assertly_jira_integration(self):
        """Test Assertly's Jira integration"""
        print("\n🔍 Testing Assertly Jira Integration...")
        try:
            # Test Assertly's Jira configuration
            response = requests.get(f"{self.assertly_url}/api/jira/projects", timeout=5)
            if response.status_code == 200:
                print("✅ Assertly Jira integration working")
                return True
            else:
                print(f"❌ Assertly Jira integration failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Assertly Jira integration test failed: {e}")
            return False
    
    def test_assertly_jira_sync(self):
        """Test Assertly's Jira synchronization"""
        print("\n🔍 Testing Assertly Jira Sync...")
        try:
            # Test sync functionality
            sync_data = {
                "project_key": "TEST",
                "sync_type": "test_cases"
            }
            
            response = requests.post(
                f"{self.assertly_url}/api/jira/sync",
                json=sync_data,
                headers={'Content-Type': 'application/json'},
                timeout=10
            )
            
            if response.status_code in [200, 201]:
                print("✅ Assertly Jira sync working")
                return True
            else:
                print(f"❌ Assertly Jira sync failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Assertly Jira sync test failed: {e}")
            return False
    
    def run_comprehensive_test(self):
        """Run comprehensive Jira integration test"""
        print("🧪 Starting Comprehensive Jira Integration Test")
        print("=" * 60)
        
        # Start Jira stub server
        self.start_jira_stub()
        
        try:
            # Test Jira stub server
            stub_tests = [
                self.test_jira_stub_health,
                self.test_jira_projects,
                self.test_jira_issues,
                self.test_jira_issue_creation
            ]
            
            stub_results = []
            for test in stub_tests:
                result = test()
                stub_results.append(result)
            
            # Test Assertly integration
            assertly_tests = [
                self.test_assertly_jira_integration,
                self.test_assertly_jira_sync
            ]
            
            assertly_results = []
            for test in assertly_tests:
                result = test()
                assertly_results.append(result)
            
            # Calculate results
            total_tests = len(stub_tests) + len(assertly_tests)
            passed_tests = sum(stub_results) + sum(assertly_results)
            success_rate = (passed_tests / total_tests) * 100
            
            print("\n" + "=" * 60)
            print("📊 TEST RESULTS SUMMARY")
            print("=" * 60)
            print(f"✅ Jira Stub Tests: {sum(stub_results)}/{len(stub_tests)} passed")
            print(f"✅ Assertly Integration Tests: {sum(assertly_results)}/{len(assertly_tests)} passed")
            print(f"📈 Overall Success Rate: {success_rate:.1f}%")
            print(f"🎯 Total Tests: {total_tests}")
            print(f"✅ Passed: {passed_tests}")
            print(f"❌ Failed: {total_tests - passed_tests}")
            
            if success_rate >= 80:
                print("\n🎉 JIRA INTEGRATION TEST: PASSED")
                print("✅ Jira integration is working correctly")
            else:
                print("\n⚠️ JIRA INTEGRATION TEST: NEEDS IMPROVEMENT")
                print("❌ Some Jira integration features need attention")
            
            return success_rate >= 80
            
        finally:
            # Stop Jira stub server
            self.stop_jira_stub()

def main():
    """Main test function"""
    print("🚀 Jira Integration Test Suite")
    print("Testing Assertly's Jira integration with stub server")
    print("=" * 60)
    
    tester = JiraIntegrationTester()
    success = tester.run_comprehensive_test()
    
    if success:
        print("\n🎉 All tests completed successfully!")
        exit(0)
    else:
        print("\n⚠️ Some tests failed. Check the output above.")
        exit(1)

if __name__ == "__main__":
    main()